### ISSUE TITLE
Problem with waitForRequest() timeout(?)

### ISSUE THREAD

**Issue by murraymichal** [HLTech/mockiavelli#20]
Hi guys,
First: I'd like to thanks for your work on this mocking tool for pptr.
Second: I have a question regarding waitForRequest: we use it after clicking save button to add some data. After the click, page is sending request to fetch new list of data on the other screen after navigating. We often get ` No request matching mock [(5) GET...`
Perhaps it's something to do with 100 ms timeout. Is it possible to increase this value from default?

**Comment by lukaszfiszer** [comment]
Hi @murraymichal, thank you for kind words. However, I'm having trouble understanding how you problem relates to `waitForRequest`. Can you provide some code sample?

**Comment by murraymichal** [comment]
`import ppExpect from 'expect-puppeteer';
 await ppExpect(testPage).toClick(saveBtn);
      await onSaveRequest.waitForRequest().then(req =>
        expect(req.body).toEqual(
          {
            name: blobName,
          }));`

Here we have flakiness. Sometimes this passes and sometimes it drops with `No request matching mock ...`

`onSaveRequest` is defined elsewhere as 
` saveRequest(): Mock {
    return this.mockiavelli.mockPOST('/save', {
      status: 201
    });
  }`

We tried using slowMo, which helps a bit but not quite (with 30 on CI it also is flaky).

**Comment by lukaszfiszer** [comment]
Are you sure that you invoke `saveRequest()`  before clicking the save button? `No request matching mock...` means that mockiavelli intercepted a request that was not (yet) mocked.  

Using `mock.waitForRequest()` will not have any effect on this. It does not halt mockiavelli's request matching, which always happens as soon request is intercepted. It just let you to halt your test until a given request is matched.

So you should always mock request **before** triggering a UI event that triggers a trigger particular request.

**Comment by lukaszfiszer** [comment]
Closing as stale issue. Please open a new one if the problem still appears.
