### ISSUE TITLE
How do I stop mocking in one session?

### ISSUE THREAD

**Issue by t-nuriakhmetov** [HLTech/mockiavelli#9]
Hi!
If i need to mock a request and then use a real one, then if there is any way to do this, other than once?
My workaround for Puppeteer: `page.setRequestInterception(false)`

**Comment by lukaszfiszer** [comment]
Sorry for taking such much time to respond - missed the notification about this issue.

Indeed, this is not possible with existing API. But we should be able to add a method like `mockiaveli.disable()` pretty easily.

**Comment by lukaszfiszer** [comment]
Actually, we may want to add 2 new public methods:

```
mockiaveli.enable(); // starts requests mocking
mockiaveli.disable(); // stops requests mocking
```

This will cover the scenario when you want to resume mocking after you stopped it. `mockiaveli.enable()` would be called when creating new instance with `Mockiavelli.setup` to keep the current behavior unchanged
